version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rezerwacja_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://db:27017/rezerwacja
    volumes:
      - .:/app:delegated
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:7
    container_name: rezerwacja_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
