# syntax=docker/dockerfile:1.7
FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=development \
    NODE_OPTIONS=--enable-source-maps

# Kopiujemy manifesty zależności
COPY package*.json ./

# Instalacja zależności (w tym devDependencies)
RUN npm install

# Kopiujemy kod aplikacji
COPY . .

# Uruchamiamy na porcie 3000 (zgodnym z .env)
EXPOSE 3000

# Użyj użytkownika node (bez root)
USER node

CMD ["npm", "run", "dev"]
