services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rezerwacja_api_dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/rezerwacje   # ✅ dopasowane do .env (nazwa DB = rezerwacje)
      - JWT_SECRET=super_secret_jwt_key           # ✅ jawnie podajemy, jak w .env
      - PORT=3000                                 # ✅ spójne z .env
    volumes:
      - .:/app
      - /app/node_modules   # chroni node_modules w kontenerze
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:7
    container_name: rezerwacja_db_dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
