# syntax=docker/dockerfile:1.7
FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=development \
    NODE_OPTIONS=--enable-source-maps

# Kopiujemy package.json i package-lock.json
COPY package*.json ./

# Instalujemy zależności (w tym nodemon z devDependencies)
RUN npm install

# Kopiujemy cały kod
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
